Profiler.java: profile type changed from ConcurrentHashMap to ConcurrentMap
ConcurrentHashMap.keySet() returns ConcurrentHashMap.KeySetView in JDK8,
but simple Set in JDK7. Thus profile.keySet() call fails with
NoSuchMethodError when compiled with JDK8, but executed on JRE7.