Add support for CONSTANT_Dynamic (#2807)
* test: added .class samples modified by jacoco

Class files modified by jacoco cause the spotbugs analysis to crash due
to #2759

* fix: upgrade BCEL to 6.8.1RC1

* fix: added partial support for CONSTANT_Dynamic

Class files using condy (Dynamic class-file constant), like JaCoCo >=
0.8.4
creates them (see [1] and [2] for more details), causes errors we using
Spotbugs to parse these class files.

The `FooWithMember.clazz` embedded in this commit has been generated
from this class source file:

```java
package com.foo;

class Foo {
    int a;

    public Foo(int a) {
        this.a = a;
    }

    public int getA() {
        return this.a;
    }
}
```

These modifications don't completely fix the support of
`CONSTANT_Dynamic`.
We continue to have error from BCEL (maybe [3] is insufficient):

```
  Exception analyzing com.foo.Foo using detector
edu.umd.cs.findbugs.detect.FindNullDeref
    java.lang.IllegalArgumentException: Unknown or invalid constant type
at 32
      At org.apache.bcel.generic.LDC.getValue(LDC.java:113)
      At edu.umd.cs.findbugs.ba.vna.ValueNumberFrameModelingVisitor.visitLDC(ValueNumberFrameModelingVisitor.java:529)
      At org.apache.bcel.generic.LDC.accept(LDC.java:58)
      At edu.umd.cs.findbugs.ba.AbstractFrameModelingVisitor.analyzeInstruction(AbstractFrameModelingVisitor.java:84)
      At edu.umd.cs.findbugs.ba.vna.ValueNumberAnalysis.transferInstruction(ValueNumberAnalysis.java:228)
      At edu.umd.cs.findbugs.ba.vna.ValueNumberAnalysis.transferInstruction(ValueNumberAnalysis.java:57)
      At edu.umd.cs.findbugs.ba.AbstractDataflowAnalysis.transfer(AbstractDataflowAnalysis.java:136)
      At edu.umd.cs.findbugs.ba.vna.ValueNumberAnalysis.transfer(ValueNumberAnalysis.java:214)
      At edu.umd.cs.findbugs.ba.vna.ValueNumberAnalysis.transfer(ValueNumberAnalysis.java:57)
      At edu.umd.cs.findbugs.ba.Dataflow.execute(Dataflow.java:378)
      At edu.umd.cs.findbugs.classfile.engine.bcel.ValueNumberDataflowFactory.analyze(ValueNumberDataflowFactory.java:76)
      At edu.umd.cs.findbugs.classfile.engine.bcel.ValueNumberDataflowFactory.analyze(ValueNumberDataflowFactory.java:46)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:368)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:321)
      At edu.umd.cs.findbugs.classfile.engine.bcel.AnalysisFactory.getValueNumberDataflow(AnalysisFactory.java:118)
      At edu.umd.cs.findbugs.classfile.engine.bcel.TypeDataflowFactory.analyze(TypeDataflowFactory.java:73)
      At edu.umd.cs.findbugs.classfile.engine.bcel.TypeDataflowFactory.analyze(TypeDataflowFactory.java:43)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:368)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:321)
      At edu.umd.cs.findbugs.classfile.engine.bcel.CFGFactory.analyze(CFGFactory.java:160)
      At edu.umd.cs.findbugs.classfile.engine.bcel.CFGFactory.analyze(CFGFactory.java:65)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:368)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:321)
      At edu.umd.cs.findbugs.classfile.engine.bcel.AnalysisFactory.getCFG(AnalysisFactory.java:93)
      At edu.umd.cs.findbugs.classfile.engine.bcel.DepthFirstSearchFactory.analyze(DepthFirstSearchFactory.java:49)
      At edu.umd.cs.findbugs.classfile.engine.bcel.DepthFirstSearchFactory.analyze(DepthFirstSearchFactory.java:32)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:368)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:321)
      At edu.umd.cs.findbugs.classfile.engine.bcel.AnalysisFactory.getDepthFirstSearch(AnalysisFactory.java:98)
      At edu.umd.cs.findbugs.classfile.engine.bcel.ValueNumberDataflowFactory.analyze(ValueNumberDataflowFactory.java:68)
      At edu.umd.cs.findbugs.classfile.engine.bcel.ValueNumberDataflowFactory.analyze(ValueNumberDataflowFactory.java:46)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:368)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:321)
      At edu.umd.cs.findbugs.ba.ClassContext.getMethodAnalysis(ClassContext.java:1010)
      At edu.umd.cs.findbugs.ba.ClassContext.getValueNumberDataflow(ClassContext.java:333)
      At edu.umd.cs.findbugs.detect.FindNullDeref.findPreviouslyDeadBlocks(FindNullDeref.java:301)
      At edu.umd.cs.findbugs.detect.FindNullDeref.analyzeMethod(FindNullDeref.java:271)
      At edu.umd.cs.findbugs.detect.FindNullDeref.visitClassContext(FindNullDeref.java:216)
      At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
      At edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$1(FindBugs2.java:1108)
      At java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
      At edu.umd.cs.findbugs.CurrentThreadExecutorService.execute(CurrentThreadExecutorService.java:86)
      At java.base/java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:247)
      At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1118)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:309)
      At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
```

[1]: https://github.com/jacoco/jacoco/commit/36b4e9c7103441d556a1667b4485960f5bdfeff8#diff-1d450b7247672d9362bac0ad7dfd7bd810e4293ab57f0100821a70a5e64e6911R56-R57
[2]: https://github.com/jacoco/jacoco/pull/845
[3]: https://issues.apache.org/jira/browse/BCEL-362

* fix: Ignore ConstantDynamic in ResolveAllReferences

* deps: reverted to using the default repos now that BCEL 6.8.1 is out

* doc: added a changelog entry

* test: converted acceptConstantDynamic to a parameterized test

---------

Co-authored-by: Jean-Baptiste Bronisz <jean-baptiste.bronisz@adevinta.com>