refs #474: reproduce problem by unit test
this test case can reproduce problem like below:

```
edu.umd.cs.findbugs.ba.Issue408Test > test FAILED
    java.lang.RuntimeException: Unable to parse classfile for module-info
        at edu.umd.cs.findbugs.classfile.engine.bcel.JavaClassAnalysisEngine.analyze(JavaClassAnalysisEngine.java:70)
        at edu.umd.cs.findbugs.classfile.engine.bcel.JavaClassAnalysisEngine.analyze(JavaClassAnalysisEngine.java:42)
        at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
        at edu.umd.cs.findbugs.classfile.engine.bcel.ClassContextClassAnalysisEngine.analyze(ClassContextClassAnalysisEngine.java:49)
        at edu.umd.cs.findbugs.classfile.engine.bcel.ClassContextClassAnalysisEngine.analyze(ClassContextClassAnalysisEngine.java:37)
        at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
        at edu.umd.cs.findbugs.ba.AnalysisContext.isTooBig(AnalysisContext.java:482)
        at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1053)
        at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:280)
        at edu.umd.cs.findbugs.test.AnalysisRunner.run(AnalysisRunner.java:119)
        at edu.umd.cs.findbugs.AbstractIntegrationTest.performAnalysis(AbstractIntegrationTest.java:126)
        at edu.umd.cs.findbugs.ba.Issue408Test.test(Issue408Test.java:19)

        Caused by:
        org.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
            at org.apache.bcel.classfile.Constant.readConstant(Constant.java:167)
            at org.apache.bcel.classfile.ConstantPool.<init>(ConstantPool.java:66)
            at org.apache.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:239)
            at org.apache.bcel.classfile.ClassParser.parse(ClassParser.java:144)
            at edu.umd.cs.findbugs.classfile.engine.bcel.JavaClassAnalysisEngine.analyze(JavaClassAnalysisEngine.java:58)
            ... 11 more

32 tests completed, 1 failed
```