Fix ignored javadoc error (#51)
* fix javac error like below

```
spotbugs/findbugs/src/java/edu/umd/cs/findbugs/annotations/NoWarning.java:17: error: reference not found
 * @deprecated The annotation based approach is useless for lambdas. Write expectations using {@link com.h3xstream.findbugs.test.matcher.BugInstanceMatcher} matchers
```

* fix "self-closing element not allowed" javadoc error

* fix class not found error.

currently matchers are put in src/junit directory, so it cannot be referred by
source in src/java.

* fix param not found error

* fix javadoc error, this is same with 9291f05263b432f576cf3ddb3b4de301f1e1225a

* fix invalid HTML

* enhance javadoc option to fail on error